{"name": "Verify User is not able to Login with Invalid credentials", "status": "passed", "description": "Verify User is not able to Login with Invalid credentials", "attachments": [{"name": "log", "source": "40c6539e-a6d8-444a-8bc0-51e2326cc8c9-attachment.txt", "type": "text/plain"}], "start": 1589022604625, "stop": 1589022621047, "uuid": "6d0479de-b76c-4032-b0d5-97bf9a142419", "historyId": "57f7ed73470ce8d4aacc4aec2dc80c63", "testCaseId": "e94f0024c374825736805ac54bd2db4c", "fullName": "tests.home.test_login.TestLogin#test_invalidLogin", "labels": [{"name": "severity", "value": "minor"}, {"name": "tag", "value": "HCMAT-54574"}, {"name": "story", "value": "HCMAT-54574"}, {"name": "parentSuite", "value": "tests.home"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "del1-lhp-N01966"}, {"name": "thread", "value": "37624-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.home.test_login"}]}