{"name": "Verify User is not able to Login with Invalid credentials", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <tests.home.test_login.TestLogin testMethod=test_invalidLogin>\n\n    @allure.story('HCMAT-54574')\n    @allure.tag('HCMAT-54574')\n    @allure.title(\"Verify User is not able to Login with Invalid credentials\")\n    @allure.description(\"Verify User is not able to Login with Invalid credentials\")\n    @allure.severity(allure.severity_level.MINOR)\n    @pytest.mark.run(order=2)\n    def test_invalidLogin(self):\n        self.log.info(\"test_invalidLogin Test is started\")\n        self.ll.login(\"test1234@email.com\",\"1234\")\n        result=self.ll.verifyLoginFailed()\n>       self.ts.markFinal(\"test_invalidLogin\", result, \"User Invalid Login\")\n\ntests\\home\\test_login.py:46: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <utilities.teststatus.TestStatus object at 0x043B04A8>, testName = 'test_invalidLogin', result = False, resultMessage = 'User Invalid Login'\n\n    def markFinal(self, testName, result, resultMessage):\n        \"\"\"\n        Mark the final result of the verification point in a test case\n        This needs to be called at least once in a test case\n        This should be final test status of the test case\n        \"\"\"\n        self.setResult(result, resultMessage)\n    \n        if \"FAIL\" in self.resultList:\n            self.log.error(testName +  \" ### TEST FAILED\")\n            self.resultList.clear()\n>           assert True == False\nE           AssertionError\n\nutilities\\teststatus.py:63: AssertionError"}, "description": "Verify User is not able to Login with Invalid credentials", "attachments": [{"name": " ", "source": "da627203-a210-4cd3-bf4b-a9d43d748d0f-attachment.png", "type": "image/png"}, {"name": "log", "source": "f4431964-6301-4326-97a4-0dd81f884d74-attachment.txt", "type": "text/plain"}], "start": 1589016411921, "stop": 1589016470266, "uuid": "ba411b99-0bc9-4e93-8e8d-ba4d6a717267", "historyId": "57f7ed73470ce8d4aacc4aec2dc80c63", "testCaseId": "e94f0024c374825736805ac54bd2db4c", "fullName": "tests.home.test_login.TestLogin#test_invalidLogin", "labels": [{"name": "tag", "value": "HCMAT-54574"}, {"name": "severity", "value": "minor"}, {"name": "story", "value": "HCMAT-54574"}, {"name": "parentSuite", "value": "tests.home"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "del1-lhp-N01966"}, {"name": "thread", "value": "36236-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.home.test_login"}]}