{"name": "Verify User is not able to Login with Invalid credentials", "status": "passed", "description": "Verify User is not able to Login with Invalid credentials", "attachments": [{"name": "log", "source": "3b312439-dff5-4605-88db-68fefa112c22-attachment.txt", "type": "text/plain"}], "start": 1589021936718, "stop": 1589021949986, "uuid": "0d0ea432-21d2-426e-a422-dab6b40b4356", "historyId": "57f7ed73470ce8d4aacc4aec2dc80c63", "testCaseId": "e94f0024c374825736805ac54bd2db4c", "fullName": "tests.home.test_login.TestLogin#test_invalidLogin", "labels": [{"name": "severity", "value": "minor"}, {"name": "tag", "value": "HCMAT-54574"}, {"name": "story", "value": "HCMAT-54574"}, {"name": "parentSuite", "value": "tests.home"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "del1-lhp-N01966"}, {"name": "thread", "value": "36108-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.home.test_login"}]}