{"name": "Verify User is not able to Login with Invalid credentials", "status": "passed", "description": "Verify User is not able to Login with Invalid credentials", "attachments": [{"name": "log", "source": "301cb82e-bc6c-4aff-83f3-9b967c3581b9-attachment.txt", "type": "text/plain"}], "start": 1589021395412, "stop": 1589021410282, "uuid": "f87bd1b1-a100-408a-a0c9-b3e96c828e39", "historyId": "57f7ed73470ce8d4aacc4aec2dc80c63", "testCaseId": "e94f0024c374825736805ac54bd2db4c", "fullName": "tests.home.test_login.TestLogin#test_invalidLogin", "labels": [{"name": "story", "value": "HCMAT-54574"}, {"name": "severity", "value": "minor"}, {"name": "tag", "value": "HCMAT-54574"}, {"name": "parentSuite", "value": "tests.home"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "del1-lhp-N01966"}, {"name": "thread", "value": "35636-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.home.test_login"}]}